-- Table: Shop Config (s)
CREATE TABLE IF NOT EXISTS `bepado_shop_config` (
  `s_shop` VARCHAR(32) NOT NULL,
  `s_config` BLOB NOT NULL,
  `changed` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`s_shop`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
